services:
  backend:
    build: ./backend
    container_name: restconf-proxy
    environment:
      # REAL RESTCONF SERVER
      - UPSTREAM_RESTCONF=http://10.0.2.2:8088/restconf
      - RESTCONF_TOKEN=your-secret-token-here
    ports:
      - "9000:9000"
    networks: [ric-net]

  frontend:
    build: ./frontend
    container_name: restconf-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks: [ric-net]

networks:
  ric-net:
    external: true
